@Bussbiljettbokningssystem_HostAddress = http://localhost:5001

GET {{Bussbiljettbokningssystem_HostAddress}}/bus/
Accept: application/json

###

GET {{Bussbiljettbokningssystem_HostAddress}}/stop/
Accept: application/json

###

GET {{Bussbiljettbokningssystem_HostAddress}}/route/
Accept: application/json

###